<a href="https://colab.research.google.com/github/MeherNaaz19/RL/blob/main/1902_UCB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
M = int(input("enter number of machines"))
machines = []
for i in range(M):
    name = input("enter machine name")
    machines.append(name)

print(machines)

enter number of machines3
enter machine nameA
enter machine nameB
enter machine nameC
['A', 'B', 'C']


In [ ]:
import numpy as np
import math as mt

N_play = 5

N = np.zeros((M, N_play))
R = np.zeros((M, N_play))
Q = np.zeros((M, N_play))
UCB = [0, 0, 0]

Q_old = 0
for machine in machines:
    print("Play with machine", machine)
    r = int(input("enter reward"))

    id = machines.index(machine)

    N[id, 0] = 1
    R[id, 0] = r

    Q[id, 0] = Q_old + (R[id, 0] - Q_old) / N[id, 0]

print(N)
print(R)
print(Q)

Play with machine A
enter reward3
Play with machine B
enter reward6
Play with machine C
enter reward4
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[3. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]]
[[3. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]]


In [ ]:
# UCB
import math as mt
play = 1
c = 2
t = 3
while(play < N_play-1):
    t = t + play
    Q[:, play] = Q[:, play-1]

    for id in range(M):

        UCB[id] = Q[id, play-1] + c * mt.sqrt( mt.log(t) / np.sum(N[id, :]))
    print(UCB)
    id_max = np.argmax(UCB)

    print("Play with machine", machines[id_max])

    r = int(input("enter reward"))

    r = int(r)

    N[id_max, play] = 1

    R[id_max, play] = r

    Q[id_max, play] = Q[id_max, play-1] + (r - Q[id_max, play-1]) / np.sum(N[id_max, :])

    play = play + 1


print(N)
print(R)
print(Q)

[np.float64(5.35482004503095), np.float64(7.053107539093664), np.float64(6.35482004503095)]
Play with machine B
enter reward7
[np.float64(5.6771323980917), np.float64(7.397250005380014), np.float64(6.6771323980917)]
Play with machine B
enter reward5
[np.float64(5.964607614735023), np.float64(7.285812830632203), np.float64(6.964607614735023)]
Play with machine B
enter reward8
[[1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]]
[[3. 0. 0. 0. 0.]
 [6. 7. 5. 8. 4.]
 [4. 0. 0. 0. 0.]]
[[3.    3.    3.    3.    3.   ]
 [6.    6.2   5.96  6.368 6.368]
 [4.    4.    4.    4.    4.   ]]
